import { normalizeText } from "@/lib/utils"

export type CountryFlagRatio = "1x1" | "4x3"

export interface LeagueRegion {
  iso: string | null
  label: string
}

/** Tên quốc gia (EN / VI / ZH) → ISO 3166-1 alpha-2 hoặc subdivision (flag-icons). */
const COUNTRY_ISO: Record<string, string> = {
  portugal: "pt",
  "bồ đào nha": "pt",
  葡萄牙: "pt",
  spain: "es",
  "tây ban nha": "es",
  西班牙: "es",
  england: "gb-eng",
  anh: "gb-eng",
  "anh quốc": "gb-eng",
  英格兰: "gb-eng",
  英國: "gb",
  germany: "de",
  đức: "de",
  德国: "de",
  德國: "de",
  france: "fr",
  pháp: "fr",
  法国: "fr",
  法國: "fr",
  italy: "it",
  ý: "it",
  italia: "it",
  意大利: "it",
  netherlands: "nl",
  holland: "nl",
  "hà lan": "nl",
  荷兰: "nl",
  荷蘭: "nl",
  belgium: "be",
  bỉ: "be",
  比利时: "be",
  "united states": "us",
  "united states of america": "us",
  usa: "us",
  "hoa kỳ": "us",
  mỹ: "us",
  美国: "us",
  brazil: "br",
  brasil: "br",
  "bra-xin": "br",
  巴西: "br",
  argentina: "ar",
  "ác-hen-ti-na": "ar",
  阿根廷: "ar",
  mexico: "mx",
  "mê-hi-cô": "mx",
  墨西哥: "mx",
  japan: "jp",
  "nhật bản": "jp",
  nhật: "jp",
  日本: "jp",
  "south korea": "kr",
  korea: "kr",
  "hàn quốc": "kr",
  hàn: "kr",
  韩国: "kr",
  韓國: "kr",
  china: "cn",
  "trung quốc": "cn",
  trung: "cn",
  中国: "cn",
  中國: "cn",
  australia: "au",
  úc: "au",
  澳大利亚: "au",
  turkey: "tr",
  "thổ nhĩ kỳ": "tr",
  土耳其: "tr",
  russia: "ru",
  nga: "ru",
  俄罗斯: "ru",
  ukraine: "ua",
  ukraina: "ua",
  乌克兰: "ua",
  poland: "pl",
  "ba lan": "pl",
  波兰: "pl",
  "czech republic": "cz",
  czechia: "cz",
  séc: "cz",
  捷克: "cz",
  croatia: "hr",
  "crô-a-ti-a": "hr",
  克罗地亚: "hr",
  scotland: "gb-sct",
  "scốt-len": "gb-sct",
  苏格兰: "gb-sct",
  switzerland: "ch",
  "thụy sĩ": "ch",
  瑞士: "ch",
  austria: "at",
  áo: "at",
  奥地利: "at",
  sweden: "se",
  "thụy điển": "se",
  瑞典: "se",
  denmark: "dk",
  "đan mạch": "dk",
  丹麦: "dk",
  norway: "no",
  "na uy": "no",
  挪威: "no",
  finland: "fi",
  "phần lan": "fi",
  芬兰: "fi",
  greece: "gr",
  "hy lạp": "gr",
  希腊: "gr",
  romania: "ro",
  rumani: "ro",
  罗马尼亚: "ro",
  bulgaria: "bg",
  "bun-ga-ri": "bg",
  保加利亚: "bg",
  serbia: "rs",
  "séc-bia": "rs",
  塞尔维亚: "rs",
  slovakia: "sk",
  "xlô-va-ki-a": "sk",
  斯洛伐克: "sk",
  hungary: "hu",
  hungaria: "hu",
  匈牙利: "hu",
  "saudi arabia": "sa",
  "ả rập xê út": "sa",
  "ả rập saudi": "sa",
  沙特: "sa",
  沙特阿拉伯: "sa",
  "united arab emirates": "ae",
  uae: "ae",
  "các tiểu vương quốc ả rập thống nhất": "ae",
  阿联酋: "ae",
  qatar: "qa",
  "ca-ta": "qa",
  卡塔尔: "qa",
  iran: "ir",
  伊朗: "ir",
  iraq: "iq",
  伊拉克: "iq",
  india: "in",
  "ấn độ": "in",
  印度: "in",
  thailand: "th",
  "thái lan": "th",
  泰国: "th",
  vietnam: "vn",
  "viet nam": "vn",
  "việt nam": "vn",
  越南: "vn",
  indonesia: "id",
  "in-đô-nê-xi-a": "id",
  印尼: "id",
  印度尼西亚: "id",
  malaysia: "my",
  "mã lai": "my",
  马来西亚: "my",
  singapore: "sg",
  "xin-ga-po": "sg",
  新加坡: "sg",
  colombia: "co",
  "cô-lôm-bi-a": "co",
  哥伦比亚: "co",
  chile: "cl",
  "chi-lê": "cl",
  智利: "cl",
  peru: "pe",
  "pê-ru": "pe",
  秘鲁: "pe",
  uruguay: "uy",
  "u-ru-goay": "uy",
  乌拉圭: "uy",
  paraguay: "py",
  "pa-ra-goay": "py",
  巴拉圭: "py",
  ecuador: "ec",
  "ê-cu-a-đo": "ec",
  厄瓜多尔: "ec",
  venezuela: "ve",
  "vê-nê-zu-ê-la": "ve",
  委内瑞拉: "ve",
  bolivia: "bo",
  "bô-li-vi-a": "bo",
  玻利维亚: "bo",
  morocco: "ma",
  maroc: "ma",
  摩洛哥: "ma",
  egypt: "eg",
  "ai cập": "eg",
  埃及: "eg",
  nigeria: "ng",
  "ni-giê-ri-a": "ng",
  尼日利亚: "ng",
  "south africa": "za",
  "nam phi": "za",
  南非: "za",
  ghana: "gh",
  "ga-na": "gh",
  加纳: "gh",
  senegal: "sn",
  "xê-nê-gan": "sn",
  塞内加尔: "sn",
  canada: "ca",
  "ca-na-đa": "ca",
  加拿大: "ca",
  "new zealand": "nz",
  "niu di-lân": "nz",
  新西兰: "nz",
  wales: "gb-wls",
  "xứ wales": "gb-wls",
  威尔士: "gb-wls",
  "northern ireland": "gb-nir",
  "bắc ireland": "gb-nir",
  北爱尔兰: "gb-nir",
  ireland: "ie",
  "cộng hòa ireland": "ie",
  爱尔兰: "ie",
  iceland: "is",
  "ais-len": "is",
  冰岛: "is",
  luxembourg: "lu",
  "lúc-xem-bua": "lu",
  卢森堡: "lu",
  cyprus: "cy",
  síp: "cy",
  塞浦路斯: "cy",
  malta: "mt",
  马耳他: "mt",
  kosovo: "xk",
  "cô-sô-vô": "xk",
  科索沃: "xk",
  albania: "al",
  "an-ba-ni": "al",
  阿尔巴尼亚: "al",
  montenegro: "me",
  "mông-tê-nê-grô": "me",
  黑山: "me",
  "north macedonia": "mk",
  macedonia: "mk",
  "bắc macedonia": "mk",
  北马其顿: "mk",
  slovenia: "si",
  "xlô-vê-ni-a": "si",
  斯洛文尼亚: "si",
  estonia: "ee",
  "e-xtô-ni-a": "ee",
  爱沙尼亚: "ee",
  latvia: "lv",
  "lát-vi-a": "lv",
  拉脱维亚: "lv",
  lithuania: "lt",
  litva: "lt",
  立陶宛: "lt",
  belarus: "by",
  "bê-la-rút": "by",
  白俄罗斯: "by",
  kazakhstan: "kz",
  "ka-dắc-xtan": "kz",
  哈萨克斯坦: "kz",
  uzbekistan: "uz",
  "ud-dơ-bê-ki-xtan": "uz",
  乌兹别克斯坦: "uz",
  georgia: "ge",
  gruzia: "ge",
  格鲁吉亚: "ge",
  armenia: "am",
  "ác-mê-ni-a": "am",
  亚美尼亚: "am",
  azerbaijan: "az",
  "a-déc-bai-gian": "az",
  阿塞拜疆: "az",
  israel: "il",
  "i-xra-en": "il",
  以色列: "il",
  jordan: "jo",
  "giót-đan": "jo",
  约旦: "jo",
  lebanon: "lb",
  "li-băng": "lb",
  黎巴嫩: "lb",
  tunisia: "tn",
  "tuy-ni-di": "tn",
  突尼斯: "tn",
  algeria: "dz",
  "an-giê-ri": "dz",
  阿尔及利亚: "dz",
  libya: "ly",
  "li-bi": "ly",
  利比亚: "ly",
  kenya: "ke",
  "kê-ni-a": "ke",
  肯尼亚: "ke",
  honduras: "hn",
  洪都拉斯: "hn",
  "costa rica": "cr",
  "cốt-xta ri-ca": "cr",
  哥斯达黎加: "cr",
  jamaica: "jm",
  牙买加: "jm",
  philippines: "ph",
  "phi-líp-pin": "ph",
  菲律宾: "ph",
  bahrain: "bh",
  "ba-ranh": "bh",
  巴林: "bh",
  kuwait: "kw",
  "cô-oét": "kw",
  科威特: "kw",
  oman: "om",
  "ô-man": "om",
  阿曼: "om",
  "north korea": "kp",
  "triều tiên": "kp",
  朝鲜: "kp",
  "bosnia and herzegovina": "ba",
  bosna: "ba",
  波黑: "ba",
  moldova: "md",
  摩尔多瓦: "md",
  "el salvador": "sv",
  萨尔瓦多: "sv",
  guatemala: "gt",
  危地马拉: "gt",
  europe: "eu",
  "european union": "eu",
  "châu âu": "eu",
  uefa: "eu",
  欧洲: "eu",
  world: "un",
  international: "un",
  "quốc tế": "un",
  "thế giới": "un",
  fifa: "un",
  国际: "un",
  世界: "un",
}

const EMPTY_LABELS = new Set(["", "khác", "other", "unknown", "n/a", "-", "null"])

const ISO_CODE_RE = /^[a-z]{2}(?:-[a-z]{2,3})?$/i

const FLAG_ICONS_CDN = "https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags"

/** regionId (API match-leagues) → cờ + nhãn. */
const REGION_BY_ID: Record<number, LeagueRegion> = {
  1: { iso: "un", label: "Quốc tế" },
  2: { iso: "eu", label: "Châu Âu" },
  3: { iso: "gb-eng", label: "Anh" },
  5: { iso: "cn", label: "Trung Quốc" },
  6: { iso: "jp", label: "Nhật Bản" },
  7: { iso: "it", label: "Ý" },
  8: { iso: "es", label: "Tây Ban Nha" },
  9: { iso: "de", label: "Đức" },
  10: { iso: "kr", label: "Hàn Quốc" },
  11: { iso: "fr", label: "Pháp" },
  12: { iso: "au", label: "Úc" },
  13: { iso: "nl", label: "Hà Lan" },
  14: { iso: "ru", label: "Nga" },
  15: { iso: "pt", label: "Bồ Đào Nha" },
  16: { iso: "th", label: "Thái Lan" },
  18: { iso: "br", label: "Brazil" },
  19: { iso: "ar", label: "Argentina" },
  20: { iso: "be", label: "Bỉ" },
  21: { iso: "sa", label: "Ả Rập Xê Út" },
  22: { iso: "cl", label: "Chile" },
  23: { iso: "co", label: "Colombia" },
  24: { iso: "us", label: "Hoa Kỳ" },
  25: { iso: "mx", label: "Mexico" },
  27: { iso: "ch", label: "Thụy Sĩ" },
  28: { iso: "tr", label: "Thổ Nhĩ Kỳ" },
  29: { iso: "uy", label: "Uruguay" },
  30: { iso: "se", label: "Thụy Điển" },
  31: { iso: "dk", label: "Đan Mạch" },
  32: { iso: "pe", label: "Peru" },
  33: { iso: "ae", label: "UAE" },
  35: { iso: "gr", label: "Hy Lạp" },
  36: { iso: "ua", label: "Ukraina" },
  37: { iso: "ir", label: "Iran" },
  39: { iso: "pl", label: "Ba Lan" },
  40: { iso: "vn", label: "Việt Nam" },
  42: { iso: "ec", label: "Ecuador" },
  43: { iso: "in", label: "Ấn Độ" },
  44: { iso: "ro", label: "Romania" },
  45: { iso: "id", label: "Indonesia" },
  46: { iso: "ca", label: "Canada" },
  47: { iso: "my", label: "Malaysia" },
  48: { iso: "cz", label: "Séc" },
  49: { iso: "at", label: "Áo" },
  50: { iso: "no", label: "Na Uy" },
  51: { iso: "fi", label: "Phần Lan" },
  52: { iso: "qa", label: "Qatar" },
  53: { iso: "iq", label: "Iraq" },
  54: { iso: "hr", label: "Croatia" },
  55: { iso: "hu", label: "Hungary" },
  58: { iso: "hn", label: "Honduras" },
  59: { iso: "py", label: "Paraguay" },
  60: { iso: "sg", label: "Singapore" },
  62: { iso: "uz", label: "Uzbekistan" },
  63: { iso: "bh", label: "Bahrain" },
  65: { iso: "ie", label: "Ireland" },
  66: { iso: "kw", label: "Kuwait" },
  67: { iso: "rs", label: "Serbia" },
  68: { iso: "jo", label: "Jordan" },
  69: { iso: "sk", label: "Slovakia" },
  70: { iso: "bg", label: "Bulgaria" },
  71: { iso: "om", label: "Oman" },
  72: { iso: "si", label: "Slovenia" },
  73: { iso: "cr", label: "Costa Rica" },
  75: { iso: "kp", label: "Triều Tiên" },
  76: { iso: "ba", label: "Bosnia" },
  78: { iso: "al", label: "Albania" },
  79: { iso: "jm", label: "Jamaica" },
  83: { iso: "is", label: "Iceland" },
  84: { iso: "gb-nir", label: "Bắc Ireland" },
  85: { iso: "bo", label: "Bolivia" },
  86: { iso: "ve", label: "Venezuela" },
  87: { iso: "gb-wls", label: "Wales" },
  89: { iso: "mk", label: "Bắc Macedonia" },
  90: { iso: "by", label: "Belarus" },
  91: { iso: "sr", label: "Suriname" },
  92: { iso: "il", label: "Israel" },
  93: { iso: "ph", label: "Philippines" },
  94: { iso: "cy", label: "Síp" },
  95: { iso: "ee", label: "Estonia" },
  96: { iso: "lv", label: "Latvia" },
  97: { iso: "lt", label: "Litva" },
  98: { iso: "lu", label: "Luxembourg" },
  99: { iso: "mt", label: "Malta" },
  100: { iso: "md", label: "Moldova" },
  101: { iso: "ge", label: "Gruzia" },
  102: { iso: "lb", label: "Lebanon" },
  104: { iso: "am", label: "Armenia" },
  105: { iso: "sv", label: "El Salvador" },
  106: { iso: "az", label: "Azerbaijan" },
  108: { iso: "gt", label: "Guatemala" },
  110: { iso: "kz", label: "Kazakhstan" },
  111: { iso: "me", label: "Montenegro" },
  112: { iso: "xk", label: "Kosovo" },
  113: { iso: "gb-sct", label: "Scotland" },
}

const NAME_HINTS: Array<{ test: RegExp; iso: string; label: string }> = [
  {
    test: /\b(int\.?\s*cf|international|fifa|world\s*cup|quốc tế|giao hữu quốc tế)\b/i,
    iso: "un",
    label: "Quốc tế",
  },
  {
    test: /\b(uefa|europa|champions league|cúp c1|cúp c[23]|euro)\b/i,
    iso: "eu",
    label: "Châu Âu",
  },
  { test: /\b(concacaf)\b/i, iso: "us", label: "Bắc Mỹ" },
  { test: /\b(conmebol|libertadores|sudamericana)\b/i, iso: "br", label: "Nam Mỹ" },
  { test: /\b(afc|asian cup)\b/i, iso: "jp", label: "Châu Á" },
  { test: /\b(caf|africa)\b/i, iso: "za", label: "Châu Phi" },
]

function isEmptyLabel(value?: string | null): boolean {
  return !value || EMPTY_LABELS.has(normalizeText(value))
}

/** Chuẩn hóa tên quốc gia hoặc mã sẵn có thành ISO (lowercase) để lấy cờ. */
export function toCountryIso(country?: string | null): string | null {
  if (isEmptyLabel(country)) return null
  const raw = country!.trim()
  if (ISO_CODE_RE.test(raw)) return raw.toLowerCase()
  return COUNTRY_ISO[normalizeText(raw)] ?? COUNTRY_ISO[raw] ?? null
}

function inferRegionFromName(leagueName?: string | null): LeagueRegion | null {
  if (!leagueName) return null
  for (const hint of NAME_HINTS) {
    if (hint.test.test(leagueName)) return { iso: hint.iso, label: hint.label }
  }
  return null
}

/** Cờ + nhãn khu vực của giải: hostCountry → regionId → tên giải → Quốc tế. */
export function resolveLeagueRegion(input: {
  hostCountry?: string | null
  regionId?: number | null
  leagueName?: string | null
}): LeagueRegion {
  const fromCountry = toCountryIso(input.hostCountry)
  if (fromCountry) {
    return {
      iso: fromCountry,
      label: isEmptyLabel(input.hostCountry)
        ? fromCountry.toUpperCase()
        : input.hostCountry!.trim(),
    }
  }

  if (input.regionId != null && REGION_BY_ID[input.regionId]) {
    return REGION_BY_ID[input.regionId]
  }

  return inferRegionFromName(input.leagueName) ?? { iso: "un", label: "Quốc tế" }
}

const NO_FLAG_ISO = new Set(["un", "xx"])

/** OpenMoji 🌍 (CC BY-SA 4.0) — dùng khi không có cờ quốc gia (quốc tế). */
const GLOBE_ICON_URL = "https://cdn.jsdelivr.net/npm/openmoji@15.1.0/color/svg/1F30D.svg"

export function hasCountryFlag(iso?: string | null): boolean {
  if (!iso) return false
  return !NO_FLAG_ISO.has(iso.trim().toLowerCase())
}

export function getGlobeIconUrl(): string {
  return GLOBE_ICON_URL
}

/**
 * URL SVG cờ từ flag-icons (MIT, https://github.com/lipis/flag-icons).
 * `iso`: alpha-2 (`vn`) hoặc subdivision (`gb-eng`).
 */
export function getCountryFlagUrl(iso: string, options?: { ratio?: CountryFlagRatio }): string {
  const code = iso.trim().toLowerCase()
  const ratio = options?.ratio ?? "4x3"
  return `${FLAG_ICONS_CDN}/${ratio}/${code}.svg`
}
